#pragma once

#include <cstdint>

enum class TwaiError : uint32_t {
  OK = 0,
  GENERAL_FAILURE,
  INVALID_STATE,
  NOT_INITIALIZED,
  ALREADY_INITIALIZED,
  TRANSMIT_FAILED,
  RECEIVE_FAILED,
  DRIVER_INSTALL_FAILED,
  DRIVER_START_FAILED,
  DRIVER_STOP_FAILED,
  DRIVER_UNINSTALL_FAILED,
  INVALID_MESSAGE,
  TIMEOUT
};
